version: 2
defaults: &defaults
  macos:
    xcode: "9.1"
    environment:
      LANG: en_US.UTF-8
jobs:
  test_swift_3:
    <<: *defaults
    steps:
      - run: brew outdated carthage || brew upgrade carthage
      - checkout      
        # Can we do SWIFT_VERSION change better than this one below?
      - run: perl -pi -w -e 's{SWIFT_VERSION = 4.0}{SWIFT_VERSION = 3.0}' Moya.xcodeproj/project.pbxproj    
      - run: bundle install
      # Only bootstrap if we have updated dependencies since our last cache.
      - restore_cache:
          keys:
            - carthage_cache_swift_3
      - run: scripts/bootstrap-if-needed.sh 
      - save_cache:
          key: carthage_cache_swift_3
          paths: 
            - Carthage      
      - run: rake test
  test_swift_4:
      <<: *defaults
      steps:
        - run: brew outdated carthage || brew upgrade carthage
        - checkout      
        # Can we do SWIFT_VERSION change better than this one below?
        - run: perl -pi -w -e 's{SWIFT_VERSION = 3.0}{SWIFT_VERSION = 4.0}' Moya.xcodeproj/project.pbxproj    
        - run: bundle install
        # Only bootstrap if we have updated dependencies since our last cache.
        - restore_cache:
            keys:
              - carthage_cache_swift_4              
        - run: scripts/bootstrap-if-needed.sh 
        - save_cache:
            key: carthage_cache_swift_4
            paths: 
              - Carthage            
        - run: rake test

  test_integration_carthage:
    <<: *defaults
    steps:
      - run: brew outdated carthage || brew upgrade carthage
      - checkout  
      - run: rake test:carthage
  build_demo:
    <<: *defaults
    steps:
      - run: curl -sS https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash           
      - checkout     
      - run: bundle install
      - run: cd Demo ; bundle exec pod repo update
      # Verbose to keep CI alive during long Specs repo setups.  
      - run: cd Demo ; bundle exec pod install --verbose
      - run: rake build_demo 
  danger_codecov:
    <<: *defaults
    steps:
      - checkout
      - run: brew install swiftlint
      - run: bundle install
      - run:
          command: |
            bundle exec danger
            bash <(curl -s https://codecov.io/bash) -J Moya                  
workflows:
  version: 2
  pr_build:
    jobs:
      - test_swift_3
      - test_swift_4
      - test_integration_carthage
      - build_demo     
      - danger_codecov:
          requires:
            - test_swift_3
            - test_swift_4
            - test_integration_carthage  
            - build_demo